-- Date:  2020-09-11
-- Author:  Christopher Mortimer
-- Desc:  Setup the schema and tables for the NFL data

drop table PRD_ADS_RLANG_NFL_DB.PLAYER;
drop table PRD_ADS_RLANG_NFL_DB.GAME_STATS;
drop table PRD_ADS_RLANG_NFL_DB.TEAM_LOOKUP;
drop table PRD_ADS_RLANG_NFL_DB.GAME_VENUE;
drop table PRD_ADS_RLANG_NFL_DB.VENUE;
drop table PRD_ADS_RLANG_NFL_DB.WEATHER;
drop table PRD_ADS_RLANG_NFL_DB.GAME;
drop table PRD_ADS_RLANG_NFL_DB.GAME_TYPE;

create table PRD_ADS_RLANG_NFL_DB.GAME_TYPE (
  GAME_TYPE_ID INTEGER NOT NULL
  , GAME_TYPE CHAR(3)
  , CONSTRAINT GAME_TYPE_ID_PK PRIMARY KEY (GAME_TYPE_ID)
)
;

-- GAME_VENUE
create table PRD_ADS_RLANG_NFL_DB.GAME_VENUE (
  GAME_VENUE_ID INTEGER NOT NULL
  , GAME_ID INTEGER NOT NULL
  , VENUE_ID INTEGER NOT NULL
  , CONSTRAINT GAME_VENUE_ID_PK PRIMARY KEY (GAME_VENUE_ID)
  , CONSTRAINT GAME_VENUE_GAME_ID_FK FOREIGN KEY (GAME_ID)
      REFERENCES PRD_ADS_RLANG_NFL_DB.GAME (GAME_ID)
  , CONSTRAINT GAME_VENUE_VENUE_ID_FK FOREIGN KEY (VENUE_ID)
      REFERENCES PRD_ADS_RLANG_NFL_DB.VENUE (VENUE_ID)
)
;

-- VENUE
create table PRD_ADS_RLANG_NFL_DB.VENUE (
  VENUE_ID INTEGER NOT NULL
  , VENUE_NAME VARCHAR(50)
  , CAPACITY INTEGER
  , SURFACE VARCHAR(50)
  , VENUE_TYPE VARCHAR(50)
  , CONSTRAINT VENUE_ID_PK PRIMARY KEY (VENUE_ID)
)
;

-- WEATHER
create table PRD_ADS_RLANG_NFL_DB.WEATHER (
  WEATHER_GAME_ID INTEGER NOT NULL
  , GAME_ID INTEGER NOT NULL
  , TEMPERATURE INTEGER
  , WEATHER_CONDITION VARCHAR(50)
  , WIND_SPEED INTEGER
  , HUMIDITY INTEGER
  , WIND_DIRECTION CHAR(3)
  , CONSTRAINT WEATHER_GAME_ID_PK PRIMARY KEY (WEATHER_GAME_ID)
  , CONSTRAINT WEATHER_GAME_ID_FK FOREIGN KEY (GAME_ID)
      REFERENCES PRD_ADS_RLANG_NFL_DB.GAME (GAME_ID)
)
;

-- GAME
create table PRD_ADS_RLANG_NFL_DB.GAME (
  GAME_ID INTEGER NOT NULL
  , GAME_TYPE_ID INTEGER NOT NULL
  , WEEK INTEGER
  , HOME_TEAM_ID INTEGER
  , AWAY_TEAM_ID INTEGER
  , CONSTRAINT GAME_ID_PK PRIMARY KEY (GAME_ID)
  , CONSTRAINT GAME_GAME_TYPE_ID_FK FOREIGN KEY (GAME_TYPE_ID)
      REFERENCES PRD_ADS_RLANG_NFL_DB.GAME_TYPE (GAME_TYPE_ID)
)
;

-- GAME_STATS
create table PRD_ADS_RLANG_NFL_DB.GAME_STATS (
  GAME_TEAM_ID INTEGER NOT NULL
  , GAME_ID INTEGER NOT NULL
  , TEAM_ID INTEGER NOT NULL
  , TOTAL_FIRST_DOWNS INTEGER
  , PASSING_FIRST_DOWNS INTEGER
  , RUSHING_FIRST_DOWNS INTEGER
  , PENALTY_FIRST_DOWNS INTEGER
  , THIRD_DOWN_ATTEMPTS INTEGER
  , THIRD_DOWN_CONVERSIONS INTEGER
  , THIRD_DOWN_CONVERSION_PERC DECIMAL(10,5)
  , THIRD_DOWN_PASSING_CONVERSIONS INTEGER
  , THIRD_DOWN_RUSHING_CONVERSIONS INTEGER
  , THIRD_DOWN_PENALTY_CONVERSIONS INTEGER
  , FOURTH_DOWN_ATTEMPTS INTEGER
  , FOURTH_DOWN_CONVERSIONS INTEGER
  , FOURTH_DOWN_CONVERSION_PERC DECIMAL(10,5)
  , FOURTH_DOWN_PASSING_CONVERSIONS INTEGER
  , FOURTH_DOWN_RUSHING_CONVERSIONS INTEGER
  , FOURTH_DOWN_PENALTY_CONVERSIONS INTEGER
  , TOTAL_PLAYS INTEGER
  , TOTAL_YARDS INTEGER
  , YARDS_PER_PLAY DECIMAL(10,5)
  , RUSHING_PLAYS INTEGER
  , RUSHING_YARDS INTEGER
  , RUSHING_YARDS_PER_PLAY DECIMAL(10,5)
  , PASSING_PLAYS INTEGER
  , PASSING_COMPLETIONS INTEGER
  , PASSING_YARDS_PER_PLAY DECIMAL(10,5)
  , INTERCEPTIONS INTEGER
  , SACKS INTEGER
  , NET_PASSING_YARDS INTEGER
  , GROSS_PASSING_YARDS INTEGER
  , SACK_YARDS INTEGER
  , TOTAL_RETURN_YARDS INTEGER
  , PUNT_RETURNS INTEGER
  , PUNT_RETURN_YARDS INTEGER
  , KICK_OFF_RETURNS INTEGER
  , KICK_OFF_RETURN_YARDS INTEGER
  , INTERCEPTION_RETURNS INTEGER
  , INTERCEPTION_RETURN_YARDS INTEGER
  , KICK_OFFS INTEGER
  , KICK_OFFS_IN_ENDZONE INTEGER
  , TOUCHBACKS INTEGER
  , PUNTS INTEGER
  , AVERAGE_PUNT_YARDS INTEGER
  , PUNTS_BLOCKED INTEGER
  , AVERAGE_NET_PUNT_YARDS INTEGER
  , PENALTIES INTEGER
  , PENALTY_YARDS INTEGER
  , FUMBLES INTEGER
  , FUMBLES_LOST INTEGER
  , TOTAL_TD INTEGER
  , PASSING_TD INTEGER
  , RUSHING_TD INTEGER
  , INTERCEPTION_TD INTEGER
  , FUMBLE_TD INTEGER
  , PUNT_RETURN_TD INTEGER
  , KICK_OFF_RETURN_TD INTEGER
  , FIELD_GOAL_RETURN_TD INTEGER
  , EXTRA_POINT_ATTEMPTS INTEGER
  , EXTRA_POINTS_MADE INTEGER
  , EXTRA_POINTS_BLOCKED INTEGER
  , TWO_POINT_CONVERSION_ATTEMPTS INTEGER
  , TWO_POINT_CONVERSIONS_MADE INTEGER
  , FIELD_GOAL_ATTEMPTS INTEGER
  , FIELD_GOALS_MADE INTEGER
  , FIELD_GOALS_BLOCKED INTEGER
  , REDZONE_VISITS INTEGER
  , REDZONE_TD INTEGER
  , REDZONE_EFFICIENCY INTEGER
  , GOAL_TO_GO_ATTEMPTS INTEGER
  , GOAL_TO_GO_TD INTEGER
  , GOAL_TO_GO_EFFICIENCY INTEGER
  , SAFETIES INTEGER
  , TURNOVERS INTEGER
  , POINTS_SCORED INTEGER
  , TIME_OF_POSSESION VARCHAR(10)
  , WIN_LOSS CHAR(1)
  , CONSTRAINT GAME_TEAM_ID_PK PRIMARY KEY (GAME_TEAM_ID)
  , CONSTRAINT GAME_STATS_GAME_ID_FK FOREIGN KEY (GAME_ID)
      REFERENCES PRD_ADS_RLANG_NFL_DB.GAME (GAME_ID)
  , CONSTRAINT GAME_STATS_TEAM_ID_FK FOREIGN KEY (TEAM_ID)
      REFERENCES PRD_ADS_RLANG_NFL_DB.TEAM_LOOKUP (TEAM_ID)
)
;

-- TEAM_LOOKUP
create table PRD_ADS_RLANG_NFL_DB.TEAM_LOOKUP (
  TEAM_ID INTEGER NOT NULL
  , TEAM VARCHAR(50)
  , TEAM_SHORT CHAR(3)
  , CONFERENCE CHAR(3)
  , DIVISION VARCHAR(10)
  , CONSTRAINT TEAM_ID_PK PRIMARY KEY (TEAM_ID)
)
;

-- PLAYER
create table PRD_ADS_RLANG_NFL_DB.PLAYER (
  GAME_PLAYER_ID INTEGER NOT NULL
  , WEEK INTEGER
  , GAME_ID INTEGER NOT NULL
  , TEAM_ID INTEGER NOT NULL
  , HOME_AWAY VARCHAR(50)
  , PLAYER_NAME VARCHAR(100)
  , FIELD_POSITION CHAR(3)
  , RUSHING_ATTEMPTS INTEGER
  , RUSHING_YARDS INTEGER
  , RUSHING_TD INTEGER
  , RECEIVING_TARGETS INTEGER
  , RECEPTIONS INTEGER
  , RECEIVING_YARDS INTEGER
  , RECEIVING_TD INTEGER
  , TOTAL_TD INTEGER
  , FUMBLES INTEGER
  , PASS_ATTEMPTS INTEGER
  , PASS_COMPLETIONS INTEGER
  , PASSING_YARDS INTEGER
  , PASSING_TD INTEGER
  , INTERCEPTIONS INTEGER
  , CONSTRAINT GAME_PLAYER_ID_PK PRIMARY KEY (GAME_PLAYER_ID)
  , CONSTRAINT PLAYER_GAME_ID_FK FOREIGN KEY (GAME_ID)
      REFERENCES PRD_ADS_RLANG_NFL_DB.GAME (GAME_ID)
  , CONSTRAINT PLAYER_TEAM_ID_FK FOREIGN KEY (TEAM_ID)
      REFERENCES PRD_ADS_RLANG_NFL_DB.TEAM_LOOKUP (TEAM_ID)
)
;
